version: '3.3'

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: atlas-colombia-api
    container_name: atlas_col_app
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8001"

volumes:
  static_volume:
  media_volume: